/**
 * @file annotation.ts
 * @description Types for human annotations made during an observe-mode session.
 *
 * Annotations are created via the overlay UI's Comment Mode — the human picks an
 * element, adds tags + a comment, and submits. They are buffered in memory with
 * full undo support (Ctrl/Cmd+Z) and flushed to the session report on browser close.
 */

// ─── Labels ──────────────────────────────────────────────────────────────────

/** Built-in annotation label presets shown as toggle chips in the modal. */
export type BuiltInAnnotationLabel = 'bug' | 'note' | 'question' | 'improvement';

/**
 * An annotation label — either one of the four built-in presets or any
 * custom string typed by the human and confirmed with Enter.
 */
export type AnnotationLabel = BuiltInAnnotationLabel | string;

// ─── Element Snapshot ────────────────────────────────────────────────────────

/** Lightweight element snapshot captured at annotation time. */
export interface AnnotationElement {
  /** Lowercase tag name, e.g. `"button"`. */
  tag: string;
  /** ARIA role or inferred role, e.g. `"button"`, `"textbox"`. */
  role?: string;
  /** Trimmed text content, capped at 120 characters. */
  text?: string;
  /** Best-effort unique CSS selector generated by the overlay. */
  selector: string;
  /** Viewport-relative bounding box at the time of annotation. */
  boundingBox: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
}

// ─── Annotation Entry ────────────────────────────────────────────────────────

/**
 * A single annotation submitted by the human during an observe session.
 * Stored in the {@link AnnotationBuffer} until session end.
 */
export interface AnnotationEntry {
  /** UUID v4 — unique per annotation. */
  id: string;
  /**
   * Zero-based index of the interaction this annotation was created after.
   * Links the annotation to a specific point in the session timeline.
   */
  interactionIndex: number;
  /** ISO 8601 timestamp of when the annotation was submitted. */
  timestamp: string;
  /** One or more labels selected/typed by the human. */
  labels: AnnotationLabel[];
  /** The human's free-text comment. */
  comment: string;
  /** The annotated element's identity and position. */
  element: AnnotationElement;
  /** Optional screenshot reference path taken at annotation time. */
  screenshotRef?: string;
}

// ─── Emoji Map (for Markdown reports) ────────────────────────────────────────

/** Maps built-in labels to their display emoji in Markdown reports. */
export const ANNOTATION_LABEL_EMOJI: Record<BuiltInAnnotationLabel, string> = {
  bug:         '🐛',
  note:        '📝',
  question:    '❓',
  improvement: '✨',
};

/** Returns a display emoji for any label (built-in or custom). */
export function getLabelEmoji(label: AnnotationLabel): string {
  return ANNOTATION_LABEL_EMOJI[label as BuiltInAnnotationLabel] ?? '🏷️';
}
