import type { ReplayBundle } from "./ReplayLoader.js";

function serializeForScript(value: unknown): string {
	return JSON.stringify(value)
		.replaceAll("<", "\\u003c")
		.replaceAll("\u2028", "\\u2028")
		.replaceAll("\u2029", "\\u2029");
}

/** Render a self-contained, offline replay UI for a persisted Talox session. */
export function renderReplayHtml(bundle: ReplayBundle): string {
	const payload = serializeForScript({ report: bundle.report, extras: bundle.extras });
	return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>Talox Replay · ${escapeHtml(bundle.report.id)}</title>
<style>
:root{color-scheme:dark;--bg:#07090c;--panel:#0d1117;--panel2:#111821;--line:#202a36;--muted:#8190a3;--text:#e8eef6;--accent:#2dd4bf;--accent2:#22d3ee;--warn:#fbbf24;--bad:#fb7185;--ok:#34d399}
*{box-sizing:border-box}html,body{height:100%;margin:0;background:var(--bg);color:var(--text);font:13px/1.45 Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;overflow:hidden}
button,select,input{font:inherit}button{color:inherit}.app{height:100%;display:grid;grid-template-rows:58px minmax(0,1fr) 76px}.topbar{display:flex;align-items:center;gap:14px;padding:0 18px;border-bottom:1px solid var(--line);background:rgba(9,13,18,.96);backdrop-filter:blur(14px)}
.brand{display:flex;align-items:center;gap:10px;font-weight:800;letter-spacing:.08em}.mark{width:30px;height:30px;border-radius:9px;display:grid;place-items:center;background:linear-gradient(135deg,var(--accent),var(--accent2));color:#041012;font-weight:950;box-shadow:0 0 26px rgba(45,212,191,.18)}.brand small{display:block;color:var(--muted);font-size:9px;letter-spacing:.18em;font-weight:700;margin-top:-2px}.session{min-width:0;flex:1}.session strong{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.session span{color:var(--muted);font-size:11px}.stats{display:flex;gap:7px}.pill{border:1px solid var(--line);border-radius:999px;padding:5px 9px;color:var(--muted);background:#0b1016}.pill b{color:var(--text);margin-left:4px}
.workspace{min-height:0;display:grid;grid-template-columns:280px minmax(320px,1fr) 330px}.panel{min-height:0;background:var(--panel)}.timeline-panel{border-right:1px solid var(--line);display:grid;grid-template-rows:auto minmax(0,1fr)}.panel-title{padding:14px 14px 11px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between}.panel-title strong{font-size:12px;letter-spacing:.06em;text-transform:uppercase}.panel-title span{font-size:10px;color:var(--muted)}
.timeline{overflow:auto;padding:8px}.event{width:100%;border:1px solid transparent;background:transparent;text-align:left;padding:9px 10px;margin:2px 0;border-radius:9px;cursor:pointer;display:grid;grid-template-columns:28px minmax(0,1fr);gap:8px;transition:.12s ease}.event:hover{background:#121a23}.event.active{background:#10201f;border-color:#1f746b;box-shadow:inset 3px 0 0 var(--accent)}.event-index{color:var(--muted);font:10px ui-monospace,SFMono-Regular,Menlo,monospace;padding-top:2px}.event-main{min-width:0}.event-type{font-size:11px;font-weight:750;text-transform:uppercase;letter-spacing:.04em}.event-desc{color:var(--muted);font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.event-flags{display:flex;gap:4px;margin-top:5px}.dot{width:6px;height:6px;border-radius:50%;background:var(--line)}.dot.bad{background:var(--bad)}.dot.warn{background:var(--warn)}.dot.note{background:var(--accent2)}
.stage{min-width:0;min-height:0;position:relative;background:radial-gradient(circle at 50% 40%,#131b24 0,#090d12 58%,#06080b 100%);display:grid;place-items:center;padding:28px}.screen-shell{position:relative;max-width:100%;max-height:100%;border:1px solid #283442;border-radius:14px;overflow:hidden;background:#05070a;box-shadow:0 30px 90px rgba(0,0,0,.45);display:grid;place-items:center}.screen-shell img{display:block;max-width:100%;max-height:calc(100vh - 190px);object-fit:contain}.empty-screen{min-width:460px;min-height:300px;display:grid;place-items:center;text-align:center;color:var(--muted);padding:40px}.empty-screen b{display:block;color:var(--text);font-size:15px;margin-bottom:5px}.target-box{position:absolute;border:2px solid var(--accent);background:rgba(45,212,191,.08);box-shadow:0 0 0 1px rgba(0,0,0,.5),0 0 18px rgba(45,212,191,.22);pointer-events:none;display:none}.frame-badge{position:absolute;left:14px;top:14px;background:rgba(5,9,13,.86);border:1px solid #293747;border-radius:8px;padding:6px 9px;color:var(--muted);font:10px ui-monospace,SFMono-Regular,Menlo,monospace;backdrop-filter:blur(10px)}.mode-toggle{position:absolute;right:14px;top:14px;display:flex;border:1px solid #293747;background:rgba(5,9,13,.86);border-radius:8px;padding:2px;backdrop-filter:blur(10px)}.mode-toggle button{border:0;background:transparent;border-radius:6px;padding:4px 8px;font-size:10px;cursor:pointer;color:var(--muted)}.mode-toggle button.active{background:#17312f;color:var(--accent)}
.inspector{border-left:1px solid var(--line);display:grid;grid-template-rows:auto minmax(0,1fr)}.inspect-scroll{overflow:auto;padding:13px}.section{padding:11px 0;border-bottom:1px solid var(--line)}.section:first-child{padding-top:0}.label{color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.12em;margin-bottom:5px}.value{overflow-wrap:anywhere}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px}.tag{display:inline-flex;align-items:center;border:1px solid var(--line);background:#101720;border-radius:6px;padding:3px 6px;margin:2px 3px 2px 0;font-size:10px}.tag.bad{border-color:#713244;color:#ff9bad}.tag.warn{border-color:#6b571b;color:#ffd86d}.tag.ok{border-color:#1e5c4b;color:#72e6bd}.issue{border-left:2px solid var(--bad);padding:6px 0 6px 9px;margin:6px 0}.issue.warn{border-color:var(--warn)}.issue b{font-size:11px}.issue div{color:var(--muted);font-size:10px;margin-top:2px}.kv{display:grid;grid-template-columns:80px minmax(0,1fr);gap:5px 9px;font-size:11px}.kv span:nth-child(odd){color:var(--muted)}
.controls{border-top:1px solid var(--line);background:#0a0e13;display:grid;grid-template-columns:auto minmax(180px,1fr) auto;align-items:center;gap:15px;padding:11px 18px}.transport{display:flex;align-items:center;gap:7px}.control{height:34px;min-width:34px;border:1px solid var(--line);border-radius:8px;background:#101720;cursor:pointer;display:grid;place-items:center}.control:hover{border-color:#365064;background:#15202b}.play{width:42px;background:#12302d;border-color:#1e6b63;color:var(--accent)}.scrub{display:grid;grid-template-columns:48px minmax(0,1fr) 48px;align-items:center;gap:9px;color:var(--muted);font:10px ui-monospace,SFMono-Regular,Menlo,monospace}.scrub input{width:100%;accent-color:var(--accent)}.speed{display:flex;align-items:center;gap:8px;color:var(--muted)}.speed select{height:32px;border:1px solid var(--line);border-radius:7px;background:#101720;color:var(--text);padding:0 8px}
@media(max-width:980px){.workspace{grid-template-columns:220px minmax(300px,1fr)}.inspector{display:none}.stats .pill:nth-child(n+3){display:none}}@media(max-width:700px){.workspace{grid-template-columns:1fr}.timeline-panel{display:none}.stage{padding:12px}.empty-screen{min-width:0}.stats{display:none}.controls{grid-template-columns:auto 1fr}.speed{display:none}}
</style>
</head>
<body>
<div class="app">
<header class="topbar">
  <div class="brand"><div class="mark">T</div><div>TALOX<small>REPLAY</small></div></div>
  <div class="session"><strong id="sessionTitle"></strong><span id="sessionMeta"></span></div>
  <div class="stats" id="stats"></div>
</header>
<main class="workspace">
  <aside class="panel timeline-panel"><div class="panel-title"><strong>Timeline</strong><span id="eventCount"></span></div><div class="timeline" id="timeline"></div></aside>
  <section class="stage"><div class="screen-shell" id="screenShell"><div class="empty-screen" id="emptyScreen"><div><b>No screenshot for this frame</b>Talox still preserved the structured interaction data.</div></div><img id="shot" alt="Session screenshot" hidden /><div class="target-box" id="targetBox"></div><div class="frame-badge" id="frameBadge"></div><div class="mode-toggle"><button id="beforeBtn">Before</button><button id="afterBtn" class="active">After</button></div></div></section>
  <aside class="panel inspector"><div class="panel-title"><strong>Inspector</strong><span id="inspectIndex"></span></div><div class="inspect-scroll" id="inspector"></div></aside>
</main>
<footer class="controls">
  <div class="transport"><button class="control" id="prevBtn" title="Previous (←)">◀</button><button class="control play" id="playBtn" title="Play/Pause (Space)">▶</button><button class="control" id="nextBtn" title="Next (→)">▶</button></div>
  <div class="scrub"><span id="elapsed">0:00</span><input id="scrubber" type="range" min="0" max="0" value="0" step="1" /><span id="duration">0:00</span></div>
  <div class="speed"><span>Speed</span><select id="speed"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option><option value="4">4×</option></select></div>
</footer>
</div>
<script>
const DATA=${payload};
const report=DATA.report;const extras=DATA.extras||{};const interactions=report.interactions||[];
let index=0,mode="after",playing=false,timer=null,speed=1;
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");
const fmtMs=ms=>{const s=Math.max(0,Math.floor((ms||0)/1000));return Math.floor(s/60)+":"+String(s%60).padStart(2,"0")};
const eventTime=i=>{if(!interactions.length)return 0;const base=Date.parse(report.startedAt);return Math.max(0,Date.parse(interactions[i].timestamp)-base)};
const safeShot=value=>{if(typeof value!=="string"||!value)return null;const v=value.replaceAll("\\\\","/");if(/^[A-Za-z0-9+/=]{100,}$/.test(v))return "data:image/png;base64,"+v;if(v.startsWith("/")||v.includes("..")||v.includes(":"))return null;return v};
function preferredShot(item){const primary=mode==="before"?item.screenshotBefore:item.screenshotAfter;const secondary=mode==="before"?item.screenshotAfter:item.screenshotBefore;return safeShot(primary)||safeShot(secondary)}
function fallbackShot(i){for(let p=i;p>=0;p--){const shot=preferredShot(interactions[p]);if(shot)return shot}return null}
function typeLabel(type){return ({click:"Click",navigation:"Navigate",input:"Input",scroll:"Scroll",rightclick:"Right click"})[type]||type}
function describe(item){if(item.element?.text)return item.element.text;if(item.element?.role)return item.element.role;if(item.element?.tag)return "<"+item.element.tag+">";try{return new URL(item.url).pathname||item.url}catch{return item.url}}
function related(list,itemIndex){return (list||[]).filter(x=>x.interactionIndex===itemIndex)}
function buildTimeline(){const root=$("timeline");root.textContent="";interactions.forEach((item,i)=>{const b=document.createElement("button");b.className="event";b.dataset.index=String(i);const flags=[];if(item.consoleErrors?.length)flags.push('<span class="dot bad"></span>');if(item.networkFailures?.length)flags.push('<span class="dot warn"></span>');if(related(extras.bugs,item.index).length)flags.push('<span class="dot note"></span>');b.innerHTML='<span class="event-index">#'+String(item.index).padStart(2,"0")+'</span><span class="event-main"><span class="event-type">'+esc(typeLabel(item.type))+'</span><span class="event-desc"></span><span class="event-flags">'+flags.join("")+'</span></span>';b.querySelector(".event-desc").textContent=describe(item);b.addEventListener("click",()=>select(i,true));root.appendChild(b)})}
function renderHeader(){$("sessionTitle").textContent="Session "+report.id;$("sessionMeta").textContent=new Date(report.startedAt).toLocaleString()+" · "+report.startUrl;const s=report.summary||{};$("stats").innerHTML='<span class="pill">Interactions <b>'+esc(s.totalInteractions??interactions.length)+'</b></span><span class="pill">Annotations <b>'+esc(s.totalAnnotations??0)+'</b></span><span class="pill">Errors <b>'+esc(s.totalConsoleErrors??0)+'</b></span><span class="pill">Failures <b>'+esc(s.totalNetworkFailures??0)+'</b></span>';$("eventCount").textContent=interactions.length+" events";$("duration").textContent=fmtMs(report.durationMs);$("scrubber").max=String(Math.max(0,interactions.length-1))}
function renderInspector(item){const bugs=related(extras.bugs,item.index);const failures=related(extras.failures,item.index);const diffs=related(extras.diffs,item.index);const el=item.element;let html='<section class="section"><div class="label">Action</div><div class="value"><span class="tag ok">'+esc(typeLabel(item.type))+'</span> <span class="mono">#'+item.index+'</span></div></section><section class="section"><div class="label">URL</div><div class="value mono" id="inspectUrl"></div></section>';
if(el){html+='<section class="section"><div class="label">Target</div><div class="kv"><span>Tag</span><span class="mono">&lt;'+esc(el.tag)+'&gt;</span><span>Role</span><span>'+esc(el.role||"—")+'</span><span>Text</span><span id="targetText"></span><span>Selector</span><span class="mono" id="targetSelector"></span><span>Box</span><span class="mono">'+esc(el.boundingBox?.x)+','+esc(el.boundingBox?.y)+' · '+esc(el.boundingBox?.width)+'×'+esc(el.boundingBox?.height)+'</span></div></section>'}
if(item.consoleErrors?.length){html+='<section class="section"><div class="label">Console errors</div>'+item.consoleErrors.map(e=>'<div class="issue"><b>Console</b><div class="issueText"></div></div>').join("")+'</section>'}
if(item.networkFailures?.length){html+='<section class="section"><div class="label">Network failures</div>'+item.networkFailures.map(n=>'<div class="issue warn"><b>'+esc(n.status)+'</b><div class="networkUrl"></div></div>').join("")+'</section>'}
if(bugs.length){html+='<section class="section"><div class="label">Detected bugs</div>'+bugs.map(b=>'<div class="issue"><b>['+esc(b.severity)+'] '+esc(b.type)+'</b><div class="bugText"></div></div>').join("")+'</section>'}
if(failures.length||diffs.length){html+='<section class="section"><div class="label">Replay context</div><div class="value">'+failures.length+' linked failures · '+diffs.length+' diffs</div></section>'}
$("inspector").innerHTML=html;$("inspectUrl").textContent=item.url;if(el){$("targetText").textContent=el.text||"—";$("targetSelector").textContent=el.selector||"—"}document.querySelectorAll(".issueText").forEach((node,i)=>node.textContent=item.consoleErrors[i]||"");document.querySelectorAll(".networkUrl").forEach((node,i)=>node.textContent=item.networkFailures[i]?.url||"");document.querySelectorAll(".bugText").forEach((node,i)=>node.textContent=bugs[i]?.description||"")}
function renderTarget(item){const box=item.element?.boundingBox;const img=$("shot"),target=$("targetBox");target.style.display="none";if(!box||img.hidden||!img.naturalWidth||!img.naturalHeight)return;target.style.left=(box.x/img.naturalWidth*100)+"%";target.style.top=(box.y/img.naturalHeight*100)+"%";target.style.width=(box.width/img.naturalWidth*100)+"%";target.style.height=(box.height/img.naturalHeight*100)+"%";target.style.display="block"}
function renderShot(item){const src=fallbackShot(index),img=$("shot"),empty=$("emptyScreen");if(!src){img.hidden=true;empty.hidden=false;$("targetBox").style.display="none";return}empty.hidden=true;img.hidden=false;if(img.getAttribute("src")!==src)img.src=src;else renderTarget(item)}
function select(next,user=false){if(!interactions.length)return;index=Math.max(0,Math.min(interactions.length-1,next));const item=interactions[index];document.querySelectorAll(".event").forEach((node,i)=>node.classList.toggle("active",i===index));const active=document.querySelector('.event[data-index="'+index+'"]');if(user&&active)active.scrollIntoView({block:"nearest"});$("inspectIndex").textContent=(index+1)+" / "+interactions.length;$("frameBadge").textContent=typeLabel(item.type).toUpperCase()+" · "+fmtMs(eventTime(index));$("scrubber").value=String(index);$("elapsed").textContent=fmtMs(eventTime(index));renderShot(item);renderInspector(item);if(playing)scheduleNext()}
function setMode(next){mode=next;$("beforeBtn").classList.toggle("active",mode==="before");$("afterBtn").classList.toggle("active",mode==="after");if(interactions[index])renderShot(interactions[index])}
function scheduleNext(){clearTimeout(timer);if(!playing)return;if(index>=interactions.length-1){playing=false;$("playBtn").textContent="▶";return}const current=eventTime(index),next=eventTime(index+1);const delay=Math.min(3000,Math.max(250,next-current))/speed;timer=setTimeout(()=>select(index+1),delay)}
function togglePlay(){playing=!playing;$("playBtn").textContent=playing?"❚❚":"▶";if(playing){if(index>=interactions.length-1)select(0);scheduleNext()}else clearTimeout(timer)}
renderHeader();buildTimeline();if(interactions.length)select(0);else{$("frameBadge").textContent="EMPTY SESSION";$("inspectIndex").textContent="0 / 0";$("inspector").innerHTML='<section class="section"><div class="label">Replay</div><div class="value">No interactions were recorded.</div></section>'}
$("shot").addEventListener("load",()=>interactions[index]&&renderTarget(interactions[index]));$("prevBtn").addEventListener("click",()=>select(index-1,true));$("nextBtn").addEventListener("click",()=>select(index+1,true));$("playBtn").addEventListener("click",togglePlay);$("scrubber").addEventListener("input",e=>select(Number(e.target.value),true));$("speed").addEventListener("change",e=>{speed=Number(e.target.value)||1;if(playing)scheduleNext()});$("beforeBtn").addEventListener("click",()=>setMode("before"));$("afterBtn").addEventListener("click",()=>setMode("after"));document.addEventListener("keydown",e=>{if(e.target&&["INPUT","SELECT","TEXTAREA"].includes(e.target.tagName))return;if(e.key==="ArrowLeft"){e.preventDefault();select(index-1,true)}else if(e.key==="ArrowRight"){e.preventDefault();select(index+1,true)}else if(e.key===" "){e.preventDefault();togglePlay()}});
</script>
</body>
</html>`;
}

function escapeHtml(value: string): string {
	return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}
